kind: Secret
apiVersion: v1

metadata:
 name: chatapp-secrets
 namespace: chatapp

type: Opaque

stringData:
  JWT_SECRET: Yjk5ZmIwMGJmNzA4ZGI0YmM4YTg1Zjc4NGU3MjljYzM3NDdhNjVlNmI3OWIzY2E5ZTVhZTY3YjQyNWM4N2Q3YmI5YWUwMzUzMWEyMDk4ZDY3YWZmODc1MWI0NTQ2MjYxZjQzMjZlMzdiYzAwOThlMzg3MzllMDlhMTIwNDI2MTk3MzhlMmRmNjllODVhNWU2ZTQ4ZDQ3NmE1N2VhNjNmZWM5ZTdkOTgxYzc4Zjg3ZDFhM2I2NmU4MzBiNjA3NDIxNjYyNmJhOTc5Y2RlMTdlYTM0Y2EwYjA5NTc2YzM3MTMwNTRjMTRhODRjNzQ1MjEwZmQwMTExNDI1YjI2OTZhMThmZWI1NWNkNTU5NzEzNzM2ZGEyZTk0NjE2NDgwODg3Njg2NGYwNDJiMTczY2I4OGM3NTk5NTUzZDE4YTMyOTgyMWUxMjRjYWI1NDk0ZmJhOGZmM2MwMjFkMDhlM2FhZTY2MTVhNjk3MTdkYTI3YzJiMmQzNTUyYzNiNmM3MTAzYWY2ZmQxZTA2NmU1M2IwMDY1Yzc1ZmQ2Y2FiMDAzMzcxNTY2ZmI1MGYxYzYyZjY5YWM2YzljMjFjY2Q2Y2JiYjhjNTAyZWI0YmQyZjZlMjE3ZWMzOGE1N2Y0Y2RiOWJkNDA4MjNhNWUzZGM2Y2IwOWY5NjY0MDNjYTljNGZhNGY=
